import type { RanchSpeciesInfo } from "./ranch.js";
export const ranchCatalog: RanchSpeciesInfo[] = [
  {
    id: "chicken",
    name: "小鸡",
    babyName: "小鸡幼崽",
    category: "farm",
    description: "黄绒绒的小团子，认真下蛋也认真散步。",
    product: "egg",
    productName: "鸡蛋",
    price: 120,
    sellPrice: 12,
    unlockLevel: 1,
    growthMs: 240000,
    cycleMs: 180000,
    harvestXp: 4,
    buyXp: 9,
    yield: 3,
  },
  {
    id: "rabbit",
    name: "垂耳兔",
    babyName: "垂耳兔幼崽",
    category: "farm",
    description: "耳朵软软，蹦起来像一朵小云。",
    product: "fur",
    productName: "兔绒",
    price: 240,
    sellPrice: 31,
    unlockLevel: 2,
    growthMs: 300000,
    cycleMs: 240000,
    harvestXp: 4,
    buyXp: 10,
    yield: 2,
  },
  {
    id: "dog",
    name: "小狗",
    babyName: "小狗幼崽",
    category: "pets",
    description: "摇尾巴的快乐管理员，最喜欢等你回来。",
    product: "dog-gift",
    productName: "伙伴徽章",
    price: 260,
    sellPrice: 34,
    unlockLevel: 2,
    growthMs: 360000,
    cycleMs: 210000,
    harvestXp: 4,
    buyXp: 10,
    yield: 2,
  },
  {
    id: "duck",
    name: "小鸭",
    babyName: "小鸭幼崽",
    category: "farm",
    description: "走路摇摇摆摆，雨天也有好心情。",
    product: "duck-gift",
    productName: "鸭蛋",
    price: 350,
    sellPrice: 30,
    unlockLevel: 3,
    growthMs: 360000,
    cycleMs: 270000,
    harvestXp: 4,
    buyXp: 11,
    yield: 3,
  },
  {
    id: "sheep",
    name: "绵羊",
    babyName: "绵羊幼崽",
    category: "farm",
    description: "云朵住进了牧场，攒下柔软的小礼物。",
    product: "sheep-gift",
    productName: "羊毛",
    price: 400,
    sellPrice: 35,
    unlockLevel: 3,
    growthMs: 450000,
    cycleMs: 360000,
    harvestXp: 4,
    buyXp: 11,
    yield: 3,
  },
  {
    id: "goose",
    name: "白鹅",
    babyName: "白鹅幼崽",
    category: "farm",
    description: "昂首挺胸的小巡逻员，其实很爱撒娇。",
    product: "goose-gift",
    productName: "鹅蛋",
    price: 450,
    sellPrice: 29,
    unlockLevel: 4,
    growthMs: 270000,
    cycleMs: 210000,
    harvestXp: 5,
    buyXp: 12,
    yield: 4,
  },
  {
    id: "goat",
    name: "山羊",
    babyName: "山羊幼崽",
    category: "farm",
    description: "好奇心满满，连食槽边也想跳一跳。",
    product: "goat-milk",
    productName: "羊奶",
    price: 480,
    sellPrice: 42,
    unlockLevel: 4,
    growthMs: 480000,
    cycleMs: 300000,
    harvestXp: 5,
    buyXp: 12,
    yield: 3,
  },
  {
    id: "cow",
    name: "奶牛",
    babyName: "奶牛幼崽",
    category: "farm",
    description: "黑白花的小伙伴，喜欢安静地嚼草。",
    product: "milk",
    productName: "牛奶",
    price: 900,
    sellPrice: 78,
    unlockLevel: 5,
    growthMs: 540000,
    cycleMs: 360000,
    harvestXp: 5,
    buyXp: 13,
    yield: 3,
  },
  {
    id: "cat",
    name: "橘猫",
    babyName: "橘猫幼崽",
    category: "pets",
    description: "把午后睡成一团，醒来给你一个蹭蹭。",
    product: "cat-gift",
    productName: "亲密徽章",
    price: 700,
    sellPrice: 61,
    unlockLevel: 5,
    growthMs: 570000,
    cycleMs: 270000,
    harvestXp: 5,
    buyXp: 13,
    yield: 3,
  },
  {
    id: "pig",
    name: "小猪",
    babyName: "小猪幼崽",
    category: "farm",
    description: "圆滚滚的开心果，把每一天吃得香香的。",
    product: "pig-gift",
    productName: "园艺肥料",
    price: 950,
    sellPrice: 82,
    unlockLevel: 6,
    growthMs: 600000,
    cycleMs: 300000,
    harvestXp: 5,
    buyXp: 14,
    yield: 3,
  },
  {
    id: "parrot",
    name: "鹦鹉",
    babyName: "鹦鹉幼崽",
    category: "pets",
    description: "叽叽喳喳的小话匣子，羽毛藏着彩虹。",
    product: "parrot-gift",
    productName: "彩色羽毛",
    price: 800,
    sellPrice: 104,
    unlockLevel: 6,
    growthMs: 540000,
    cycleMs: 240000,
    harvestXp: 5,
    buyXp: 14,
    yield: 2,
  },
  {
    id: "turtle",
    name: "小乌龟",
    babyName: "小乌龟幼崽",
    category: "pets",
    description: "慢一点也没关系，它从不忘记向前走。",
    product: "turtle-gift",
    productName: "慢生活徽章",
    price: 880,
    sellPrice: 76,
    unlockLevel: 6,
    growthMs: 450000,
    cycleMs: 300000,
    harvestXp: 5,
    buyXp: 14,
    yield: 3,
  },
  {
    id: "horse",
    name: "小马",
    babyName: "小马幼崽",
    category: "farm",
    description: "轻快的小跑步冠军，风里都是自由。",
    product: "horse-gift",
    productName: "幸运马蹄",
    price: 1250,
    sellPrice: 108,
    unlockLevel: 7,
    growthMs: 720000,
    cycleMs: 360000,
    harvestXp: 5,
    buyXp: 15,
    yield: 3,
  },
  {
    id: "frog",
    name: "青蛙",
    babyName: "青蛙幼崽",
    category: "pets",
    description: "圆眼睛的小歌手，爱在池塘边打节拍。",
    product: "frog-gift",
    productName: "池塘徽章",
    price: 1050,
    sellPrice: 91,
    unlockLevel: 7,
    growthMs: 480000,
    cycleMs: 270000,
    harvestXp: 5,
    buyXp: 15,
    yield: 3,
  },
  {
    id: "peacock",
    name: "孔雀",
    babyName: "孔雀幼崽",
    category: "zoo",
    description: "每天都盛装登场，送你一片漂亮尾羽。",
    product: "peacock-gift",
    productName: "孔雀羽毛",
    price: 1600,
    sellPrice: 104,
    unlockLevel: 8,
    growthMs: 630000,
    cycleMs: 360000,
    harvestXp: 6,
    buyXp: 16,
    yield: 4,
  },
  {
    id: "fox",
    name: "小狐狸",
    babyName: "小狐狸幼崽",
    category: "zoo",
    description: "尖耳朵里藏着好奇，尾巴暖暖像围巾。",
    product: "fox-gift",
    productName: "森林徽章",
    price: 1450,
    sellPrice: 126,
    unlockLevel: 8,
    growthMs: 660000,
    cycleMs: 300000,
    harvestXp: 6,
    buyXp: 16,
    yield: 3,
  },
  {
    id: "alpaca",
    name: "羊驼",
    babyName: "羊驼幼崽",
    category: "farm",
    description: "表情呆萌又认真，毛茸茸地陪你发呆。",
    product: "alpaca-gift",
    productName: "羊驼绒",
    price: 1850,
    sellPrice: 120,
    unlockLevel: 9,
    growthMs: 840000,
    cycleMs: 390000,
    harvestXp: 6,
    buyXp: 17,
    yield: 4,
  },
  {
    id: "hedgehog",
    name: "刺猬",
    babyName: "刺猬幼崽",
    category: "pets",
    description: "一颗会走路的小栗子，内心比肚皮还软。",
    product: "hedgehog-gift",
    productName: "松果徽章",
    price: 1650,
    sellPrice: 143,
    unlockLevel: 9,
    growthMs: 600000,
    cycleMs: 330000,
    harvestXp: 6,
    buyXp: 17,
    yield: 3,
  },
  {
    id: "deer",
    name: "梅花鹿",
    babyName: "梅花鹿幼崽",
    category: "zoo",
    description: "轻轻走过草地，身上的斑点像星星。",
    product: "deer-gift",
    productName: "鹿角纪念章",
    price: 2100,
    sellPrice: 182,
    unlockLevel: 10,
    growthMs: 540000,
    cycleMs: 300000,
    harvestXp: 6,
    buyXp: 18,
    yield: 3,
  },
  {
    id: "owl",
    name: "猫头鹰",
    babyName: "猫头鹰幼崽",
    category: "pets",
    description: "大眼睛的晚安守护者，喜欢安静陪伴。",
    product: "owl-gift",
    productName: "月亮羽毛",
    price: 2000,
    sellPrice: 173,
    unlockLevel: 10,
    growthMs: 720000,
    cycleMs: 360000,
    harvestXp: 6,
    buyXp: 18,
    yield: 3,
  },
  {
    id: "penguin",
    name: "企鹅",
    babyName: "企鹅幼崽",
    category: "zoo",
    description: "穿着小礼服，却总是走得摇摇晃晃。",
    product: "penguin-gift",
    productName: "雪地徽章",
    price: 2600,
    sellPrice: 169,
    unlockLevel: 11,
    growthMs: 690000,
    cycleMs: 450000,
    harvestXp: 6,
    buyXp: 19,
    yield: 4,
  },
  {
    id: "snake",
    name: "小蛇",
    babyName: "小蛇幼崽",
    category: "zoo",
    description: "弯成一个友好的问号，温柔地探头看看。",
    product: "snake-gift",
    productName: "鳞片纪念章",
    price: 2350,
    sellPrice: 204,
    unlockLevel: 11,
    growthMs: 780000,
    cycleMs: 390000,
    harvestXp: 6,
    buyXp: 19,
    yield: 3,
  },
  {
    id: "buffalo",
    name: "水牛",
    babyName: "水牛幼崽",
    category: "farm",
    description: "沉稳可靠的大伙伴，午睡也特别认真。",
    product: "buffalo-gift",
    productName: "水牛奶",
    price: 3000,
    sellPrice: 195,
    unlockLevel: 12,
    growthMs: 960000,
    cycleMs: 480000,
    harvestXp: 7,
    buyXp: 20,
    yield: 4,
  },
  {
    id: "moose",
    name: "驼鹿",
    babyName: "驼鹿幼崽",
    category: "zoo",
    description: "大大的鹿角，藏着一整个森林故事。",
    product: "moose-gift",
    productName: "苔原纪念章",
    price: 2800,
    sellPrice: 243,
    unlockLevel: 12,
    growthMs: 900000,
    cycleMs: 420000,
    harvestXp: 7,
    buyXp: 20,
    yield: 3,
  },
  {
    id: "zebra",
    name: "斑马",
    babyName: "斑马幼崽",
    category: "zoo",
    description: "把黑白条纹穿得漂亮，跑起来像小旋风。",
    product: "zebra-gift",
    productName: "条纹纪念章",
    price: 3300,
    sellPrice: 214,
    unlockLevel: 13,
    growthMs: 1020000,
    cycleMs: 480000,
    harvestXp: 7,
    buyXp: 21,
    yield: 4,
  },
  {
    id: "bear",
    name: "小熊",
    babyName: "小熊幼崽",
    category: "zoo",
    description: "圆耳朵加小肚腩，最爱甜甜的好日子。",
    product: "bear-gift",
    productName: "蜂蜜罐",
    price: 3200,
    sellPrice: 277,
    unlockLevel: 13,
    growthMs: 1080000,
    cycleMs: 510000,
    harvestXp: 7,
    buyXp: 21,
    yield: 3,
  },
  {
    id: "monkey",
    name: "猴子",
    babyName: "猴子幼崽",
    category: "zoo",
    description: "灵巧的小顽皮，总能发现藏起来的果子。",
    product: "monkey-gift",
    productName: "果篮",
    price: 3600,
    sellPrice: 312,
    unlockLevel: 14,
    growthMs: 600000,
    cycleMs: 300000,
    harvestXp: 7,
    buyXp: 22,
    yield: 3,
  },
  {
    id: "gorilla",
    name: "大猩猩",
    babyName: "大猩猩幼崽",
    category: "zoo",
    description: "看起来壮壮的，照顾伙伴却特别细心。",
    product: "gorilla-gift",
    productName: "雨林纪念章",
    price: 3900,
    sellPrice: 254,
    unlockLevel: 14,
    growthMs: 900000,
    cycleMs: 420000,
    harvestXp: 7,
    buyXp: 22,
    yield: 4,
  },
  {
    id: "giraffe",
    name: "长颈鹿",
    babyName: "长颈鹿幼崽",
    category: "zoo",
    description: "脖子伸向阳光，看见更远处的好风景。",
    product: "giraffe-gift",
    productName: "高高纪念章",
    price: 4400,
    sellPrice: 286,
    unlockLevel: 15,
    growthMs: 1200000,
    cycleMs: 540000,
    harvestXp: 7,
    buyXp: 23,
    yield: 4,
  },
  {
    id: "rhino",
    name: "犀牛",
    babyName: "犀牛幼崽",
    category: "zoo",
    description: "厚实的小外套里，装着一颗软乎乎的心。",
    product: "rhino-gift",
    productName: "草原纪念章",
    price: 4600,
    sellPrice: 399,
    unlockLevel: 15,
    growthMs: 1260000,
    cycleMs: 570000,
    harvestXp: 7,
    buyXp: 23,
    yield: 3,
  },
  {
    id: "hippo",
    name: "河马",
    babyName: "河马幼崽",
    category: "zoo",
    description: "泡在池塘里的大团子，笑起来嘴巴弯弯。",
    product: "hippo-gift",
    productName: "水花纪念章",
    price: 5000,
    sellPrice: 325,
    unlockLevel: 16,
    growthMs: 1080000,
    cycleMs: 450000,
    harvestXp: 8,
    buyXp: 24,
    yield: 4,
  },
  {
    id: "crocodile",
    name: "鳄鱼",
    babyName: "鳄鱼幼崽",
    category: "zoo",
    description: "晒太阳的高手，闭眼就变成一截小木头。",
    product: "crocodile-gift",
    productName: "池岸纪念章",
    price: 5200,
    sellPrice: 338,
    unlockLevel: 16,
    growthMs: 1320000,
    cycleMs: 600000,
    harvestXp: 8,
    buyXp: 24,
    yield: 4,
  },
  {
    id: "lion",
    name: "狮子",
    babyName: "狮子幼崽",
    category: "zoo",
    description: "一圈蓬松小鬃毛，把威风藏进哈欠里。",
    product: "lion-gift",
    productName: "狮王纪念章",
    price: 5800,
    sellPrice: 377,
    unlockLevel: 17,
    growthMs: 1440000,
    cycleMs: 630000,
    harvestXp: 8,
    buyXp: 25,
    yield: 4,
  },
  {
    id: "elephant",
    name: "大象",
    babyName: "大象幼崽",
    category: "zoo",
    description: "长鼻子轻轻一卷，就把温柔送到你面前。",
    product: "elephant-gift",
    productName: "象鼻纪念章",
    price: 6400,
    sellPrice: 416,
    unlockLevel: 18,
    growthMs: 1560000,
    cycleMs: 660000,
    harvestXp: 8,
    buyXp: 26,
    yield: 4,
  },
  {
    id: "panda",
    name: "大熊猫",
    babyName: "大熊猫幼崽",
    category: "zoo",
    description: "黑眼圈的治愈专家，抱着竹子就很幸福。",
    product: "panda-gift",
    productName: "竹筒纪念章",
    price: 6800,
    sellPrice: 442,
    unlockLevel: 18,
    growthMs: 1500000,
    cycleMs: 600000,
    harvestXp: 8,
    buyXp: 26,
    yield: 4,
  },
  {
    id: "sloth",
    name: "树懒",
    babyName: "树懒幼崽",
    category: "zoo",
    description: "慢慢伸个懒腰，提醒你今天也别太着急。",
    product: "sloth-gift",
    productName: "悠闲纪念章",
    price: 7600,
    sellPrice: 494,
    unlockLevel: 20,
    growthMs: 1800000,
    cycleMs: 720000,
    harvestXp: 9,
    buyXp: 28,
    yield: 4,
  },
];
