from pathlib import Path
import json
ROOT=Path('/opt/pair-play-worktrees/ranch-generated-variants')
for old,new in [('ranch-mutation-appearance','ranch-generated-appearance'),('ranch-mutation-ui','ranch-generated-ui')]:
    content=(ROOT/f'scripts/{old}-qa.mjs').read_text().replace(old,new)
    (ROOT/f'scripts/{new}-qa.mjs').write_text(content)
text=(ROOT/'apps/web/src/games/animal-ranch/generated-atlas-metadata.ts').read_text()
metadata=json.loads(text.split(' = ',1)[1].rstrip(';\n'))
folder=ROOT/'artifacts/ranch-generated-preview'
folder.mkdir(parents=True,exist_ok=True)
(folder/'metadata.json').write_text(json.dumps(metadata))
link=folder/'ranch'
if not link.exists(): link.symlink_to(ROOT/'apps/web/public/ranch',target_is_directory=True)
(folder/'index.html').write_text('''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>一起牧场 · 属性外观验收</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f4f8f2;color:#233d35;font:16px system-ui}header{padding:28px max(20px,4vw);background:white;border-bottom:1px solid #e1e9df}h1{margin:4px 0 12px;font-size:28px}p{color:#65756b;line-height:1.7}nav{display:flex;flex-wrap:wrap;gap:10px}button{border:1px solid #d5e2d1;border-radius:14px;padding:12px 16px;background:white;color:inherit;cursor:pointer}button.active{background:#355c48;color:white}main{padding:20px max(12px,4vw)}.row{display:grid;grid-template-columns:90px repeat(5,minmax(160px,1fr));gap:12px;margin-bottom:12px;align-items:center}.scroll{overflow-x:auto}.name{font-weight:700}.card{border-radius:18px;border:1px solid #d4e1ca;background:#e4efc8;overflow:hidden;text-align:center;box-shadow:0 3px 12px #2c482a09}.card canvas{display:block;width:100%;aspect-ratio:1.15}.tag{background:#fffdf1;padding:8px}.head{position:sticky;top:0;background:#f4f8f2;z-index:2;padding:8px 0;font-weight:600}small{display:block;color:#6d7d70;margin-top:16px}</style>
<header><p>一起牧场 / 新 Worktree 预览</p><h1>原来的小动物，新的属性气质</h1><p>毛色、材质和属性氛围一起生成。下面使用实际游戏图片与裁切数据，展示幼年与成年四帧动作；这是外观验收页。</p><nav id="stages"></nav><nav id="groups" style="margin-top:12px"></nav><small id="status">正在加载…</small></header><main><div class="scroll"><div id="grid"></div></div></main>
<script type="module">
const metadata=await(await fetch('metadata.json')).json();const groups=[['小鸡','垂耳兔','小狗','小鸭','绵羊','白鹅','山羊','奶牛','小猫'],['小猪','鹦鹉','乌龟','小马','青蛙','孔雀','狐狸','羊驼','刺猬'],['鹿','猫头鹰','企鹅','蛇','水牛','驼鹿','斑马','熊','猴子'],['大猩猩','长颈鹿','犀牛','河马','鳄鱼','狮子','大象','熊猫','树懒']];const attrs=['lightning','fire','water','gold','dream'],labels=['雷 · 雷弧','火 · 焰光','水 · 水波','黄金 · 金辉','梦幻 · 星雾'];let stage='adult',group=0,version=0,draw=[];const cache=new Map();function image(url){if(!cache.has(url))cache.set(url,new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=url}));return cache.get(url)}
async function show(){const token=++version;draw=[];document.querySelector('#stages').innerHTML=['adult','baby'].map(x=>`<button data-stage="${x}" class="${x===stage?'active':''}">${x==='adult'?'成年':'幼年'}</button>`).join('');document.querySelector('#groups').innerHTML=groups.map((_,i)=>`<button data-group="${i}" class="${i===group?'active':''}">动物组 ${i+1}</button>`).join('');document.querySelector('#status').textContent='加载当前 5 张图集…';const grid=document.querySelector('#grid');grid.innerHTML='<div class="row head"><div>动物</div>'+labels.map(x=>`<div>${x}</div>`).join('')+'</div>'+groups[group].map((name,i)=>`<div class="row"><div class="name">${name}</div>${attrs.map(a=>`<div class="card"><canvas width="320" height="280" data-row="${i}" data-attr="${a}"></canvas><div class="tag">${stage==='adult'?'成年':'幼年'}</div></div>`).join('')}</div>`).join('');try{const imgs=await Promise.all(attrs.map(a=>image(metadata[`${stage}-${a}-${group}-v1`].url)));if(token!==version)return;draw=[...grid.querySelectorAll('canvas')].map(c=>({c,ctx:c.getContext('2d'),atlas:metadata[`${stage}-${c.dataset.attr}-${group}-v1`],im:imgs[attrs.indexOf(c.dataset.attr)],row:+c.dataset.row}));document.querySelector('#status').textContent='当前 45 款外观已就绪 · 共 360 款 / 1440 帧'}catch{document.querySelector('#status').textContent='图片未就绪，请稍后刷新'}}
document.addEventListener('click',e=>{if(e.target.dataset.stage){stage=e.target.dataset.stage;show()}if(e.target.dataset.group){group=+e.target.dataset.group;show()}});function paint(t){const col=Math.floor(t/220)%4;for(const d of draw){const f=d.atlas.rows[d.row].frames[col],s=Math.min(185/Math.max(f.bodyWidth,f.bodyHeight),260/f.width,240/f.height);d.ctx.clearRect(0,0,320,280);d.ctx.fillStyle='#344f2726';d.ctx.beginPath();d.ctx.ellipse(160,240,Math.min(60,f.bodyWidth*s*.35),9,0,0,Math.PI*2);d.ctx.fill();d.ctx.drawImage(d.im,f.x,f.y,f.width,f.height,160-f.centerX*s,240-f.ground*s,f.width*s,f.height*s)}requestAnimationFrame(paint)}show();requestAnimationFrame(paint);
</script></html>''')
print('Prepared isolated QA scripts and static art gallery')
